--Types of Joins:
--Inner Joins - Syntax - INNER JOIN OR JOIN - combines rows from each table that match a row form the other table based on the joining condition - Example: If there is order_id in both tables, that order_id will be returned. If one table has order_id, but the other does not, it will not be returned in the table
--Inner join simplified definition: The intersection of the two tables - The commonalities of the two tables
--OUTER JOINS - 3 kinds
---1)LEFT JOIN returns only unmatched rows from the left table, as well as matched rows in both tables. SYNTAX - LEFT JOIN
---2)RIGHT JOIN returns only unmatched rows from the right table , as well as matched rows in both tables. SYNTAX - RIGHT JOIN
---3)FULL OUTER JOIN returns unmatched rows from both tables,as well as matched rows in both tables. SYNTAX - FULL JOIN
--IF unsure of the way the above work, draw a Venn diagram. Inner joins get the middle, left gets the left circle, right gets the right circle, and outer gets both

--Goal: Join customer, order, and revenue data to understand where revenue comes from and who generates it.
--Task: Write 5 queries that answer busimess questions using joins:
--1)How many orders come from each customer country?
SELECT 
  users.country,
  COUNT(orders.order_id) AS order_quanitity
FROM
  `bigquery-public-data.thelook_ecommerce.users` users
JOIN
    `bigquery-public-data.thelook_ecommerce.orders` orders
ON
  users.id = orders.user_id
WHERE
 users.country IS NOT NULL 
GROUP BY
  users.country DESC
--2)How much revenue is generated by customers in each country?
SELECT 
  users.country,
  ROUND(SUM(order_items.sale_price),2) AS revenue
FROM
  `bigquery-public-data.thelook_ecommerce.users` users
 INNER JOIN
    `bigquery-public-data.thelook_ecommerce.order_items` order_items
ON
  users.id = order_items.user_id
WHERE
  users.country IS NOT NULL
  AND order_items.status = "Complete"
GROUP BY
  users.country
ORDER BY
  revenue DESC
--3)What is the average revenue per order in each country?
--NOTES - this one was my first time using a CTE (common table expression)
  --I first tried to group by country and then order_id, but realized that I was getting multiple order_ids per country. I wanted a single AVG price per country, so i need to get more granular. My first attempt was the query in the "WITH" section of the below query. It created the substructure needed to achieve the goal, then I added in the extra layer of analysis and it worked.
  --I prefer the formatting of the below query as well. It is easier to read than the queries above.
WITH order_revenue AS (
  SELECT
    oi.order_id,
    u.country,
    SUM(oi.sale_price) AS order_revenue
  FROM `bigquery-public-data.thelook_ecommerce.order_items` AS oi
  JOIN `bigquery-public-data.thelook_ecommerce.users` AS u
    ON oi.user_id = u.id
  WHERE u.country IS NOT NULL
  GROUP BY oi.order_id, u.country
)

SELECT
  r.country,
  ROUND(AVG(r.order_revenue), 2) AS avg_order_value
FROM order_revenue AS r
GROUP BY r.country
ORDER BY avg_order_value DESC;
--4)Who are the top 10 customers by total spend?
  --NOTES - my first attempt did not include (first, last, email). I got an answer, but it didn't mean anything to me. ID's are great ways to perform analysis, but they don't give business insights that are valuable or actionable.
SELECT
  u.id AS user_id,
  u.first_name,
  u.last_name,
  u.email,
  ROUND(SUM(oi.sale_price),2) AS total_spend
FROM `bigquery-public-data.thelook_ecommerce.users` u
JOIN `bigquery-public-data.thelook_ecommerce.order_items` oi
ON oi.user_id = u.id
GROUP BY u.id,u.first_name,u.last_name,u.email
ORDER BY total_spend DESC
LIMIT 10
--5)How does revenue break down by order status and customer country?
SELECT
  u.country AS country,
  oi.status AS order_status,
  ROUND(SUM(oi.sale_price),2) AS revenue
FROM `bigquery-public-data.thelook_ecommerce.users` u
JOIN `bigquery-public-data.thelook_ecommerce.order_items` oi
ON oi.user_id = u.id
WHERE u.country IS NOT NULL
GROUP BY u.country, oi.status
ORDER BY u.country, revenue DESC
